-- This file is kept for reference. 
-- For local SQLite database, use schema.sql instead.
-- 
-- This was the original Supabase schema. The system now uses
-- a local IndexedDB database (browser) or SQLite (when deployed as EXE).
--
-- See src/database/schema.sql for the SQLite schema file.